#!/bin/bash

if [ -e "www.pid" ]; then
    PID=`cat www.pid`
    echo 'killing process:'$PID
    kill -INT $PID
    rm www.pid
    sleep 1 # allow the kill to complete
    mv www.log www.log.$PID
else
    echo no process to kill
fi
