#!/bin/bash
# make a tarball of the server for web APIs without docker

rm -rf tests/out/*
tar -cf t.tar calc/*py www/config www/*py www/*sh tests xtar
scp t.tar kolossus:/hive/groups/hexmap/dev/compute
